name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-02"

[build]
command = "cargo install -q worker-build && worker-build --release"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
USER_ID = "a4c83509-8187-4d51-afb3-2b9d437ea7fe" # your uuid
FALLBACK_SITE = "https://example.com" # https://httpbin.org/status/404
